[workspace]
authors = ["Tom Kelly <kelly.tom.734@gmail.com>"]
channels = ["https://conda.modular.com/max-nightly", "conda-forge"]
name = "rw_squirrel_3"
platforms = ["linux-64"]
version = "0.2.0"

[tasks]
run = "mojo run -I src src/main.mojo"
test = "mojo run -I src -I test test/test_id_allocator.mojo && mojo run -I src -I test test/test_index.mojo && mojo run -I src -I test test/test_entity.mojo && mojo run -I src -I test test/test_parser.mojo && mojo run -I src -I test test/test_codegen.mojo && mojo run -I src -I test test/test_json.mojo"
build = { cmd = "mojo build -I src -o squirrelc src/main.mojo" }

[dependencies]
mojo = ">=1.0.0b3.dev2026071405,<2"
